server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useSSL=false
    username: root
    password: 18729231365wzt
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: orderserver # user的服务的名称

  cloud:
    nacos:  # nacos
      server-addr: localhost:8848 # nacos 服务地址

      discovery:
        cluster-name: HZ # 集群名称
#        namespace: 4e9a3d11-5691-495c-b4d7-1add04ea3449 # 命名空间，填ID  在Nacos中心 中设置,不同的命名空间是不能被访问到的

    # 配置sentinel的控制台地址
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel的控制台地址
      web-context-unify: false # 关闭context整合

      datasource: # sentinel规则的持久化
        flow:
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: orderservice-flow-rules # nacos 中的配置id
            groupId: SENTINEL_GROUP # 组
            rule-type: flow # 还可以是：degrade、authority、param-flow

userservice:
  ribbon:                              # 发送请求会优先找与自己相同的集群
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: orderserver # 指定对应这个服务 进行饥饿加载   可多个 [..,..,..,]

# 自定义Feign的配置:
feign:
  client:
    config:
      default: # 这里如果是default就表示全局配置。如果写服务名称，则是针对某个微服务的配置
        loggerLevel: NONE # 日志级别
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数

  sentinel:
    enabled: true # 开启Feign的Sentinel功能

#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS