server:
  port: 10010 # 网关端口

spring:
  application:
    name: gateway # 服务名称

  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址

    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否以/user开头，如果是 则符合
#          filters:  # 过滤器

        - id: order-service
          uri: lb://orderserver
          predicates:
            - Path=/order/**

      default-filters:
        - AddRequestHeader=origin,gateway # 添加名为origin的请求头，值为gateway

      globalcors:  # 全局的跨域处理
        add-to-simple-url-handler-mapping: true  # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许那些网站的跨域请求  只有ajax发送的请求才会有
              - "http://127.0.0.1:8090"
              - "http://www.leyon.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的请求消息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
