server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima?useSSL=false
    username: root
    password: 18729231365wzt
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 192.168.200.130
    port: 5672
    username: wzt
    password: wzt
    virtual-host: /wztcast


logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo